# Generated by Django 5.0.7 on 2026-06-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
